export PATH=${PATH}:~/bin
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
export ARCHFLAGS="-arch i386 -arch x86_64"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function


# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

if [ -f ~/.bash_alias ]; then
  source ~/.bash_alias
fi

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
